import { ProviderWrapper } from '@/components/providers/ProviderWrapper';
import { Toaster } from "@/components/ui/sonner"
import { geist } from '@/config/page';
import { routing } from '@/i18n/routing';
import type { Metadata } from 'next';
import { hasLocale } from 'next-intl';
import { notFound } from 'next/navigation';
import '@/config/globals.css';
import { Header } from '@/components/Header';
import { Footer } from '@/components/Footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type RootLayoutProps = {
  children: React.ReactNode,
  params: Promise<{ locale: string }>,
};
export default async function RootLayout({ children, params }: Readonly<RootLayoutProps>) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  return (
    <html
      lang={locale}
      suppressHydrationWarning
    >
      <body className={geist.className}>
        <ProviderWrapper>
          <Header/>
          <main>
            <Toaster position='top-right'/>
            {children}
          </main>
          <Footer/>
        </ProviderWrapper>
      </body>
    </html>
  );
}
